"""Increase password column size

Revision ID: 308dc712c804
Revises: 6aed83d3fb79
Create Date: 2024-08-06 14:39:07.239284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308dc712c804'
down_revision = '6aed83d3fb79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
