"""updated models,added endpoints,validations,crud

Revision ID: 3d4cd2924cf9
Revises: d8feb11f5317
Create Date: 2024-07-31 20:45:13.284762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d4cd2924cf9'
down_revision = 'd8feb11f5317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
