"""Remove notes column from Booking model

Revision ID: 7d6569b97e9e
Revises: 3d4cd2924cf9
Create Date: 2024-07-31 20:53:12.969301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d6569b97e9e'
down_revision = '3d4cd2924cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
