"""Add price field to Inventory model

Revision ID: ac2ba1aafa1d
Revises: 7d6569b97e9e
Create Date: 2024-08-04 13:26:47.506269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac2ba1aafa1d'
down_revision = '7d6569b97e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False, server_default='0.0'))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
