"""Add quantity to Inventory model

Revision ID: fc1d6a880b46
Revises: 28ba7f4e06f8
Create Date: 2024-08-08 03:16:51.294093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1d6a880b46'
down_revision = '28ba7f4e06f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
